portfolio/__init__.py
from flask import Flask

from portfolio.routes import pages


def create_app():
    app = Flask(__name__)

    app.register_blueprint(pages)
    return app

portfolio/routes.py
from flask import Blueprint, render_template, abort


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


projects = [
    {
        "name": "Final Year Project: Autonomous Mobile Robot",
        "thumb": "img/AMR.jpg",
        "hero": "img/AMR.jpg",
        "categories": ["FYP", "Robotics"],
        "slug": "amr",
        "prod": "https://openaccess.cms-conferences.org/publications/book/978-1-958651-11-7/article/978-1-958651-11-7_5",
    },
    {
        "name": "Highway Lane Detection using OpenCV",
        "thumb": "img/lane_detection.png",
        "hero": "img/lane_detection.png",
        "categories": ["Computer Vision"],
        "slug": "highway_lane_detection",
        "prod": "https://github.com/Ammar2k/CV-Projects/tree/master/Highway_Lanes",
    },
    {
        "name": "Traffic Sign Classification",
        "thumb": "img/road_work.png",
        "hero": "img/road_work.png",
        "categories": ["Deep Learning", "CNN"],
        "slug": "traffic_sign_classification",
        "prod": "https://github.com/Ammar2k/CV-Projects/tree/master/traffic_sign_classification",
    },
    # {
    #     "name": "Habit tracking app with Python and MongoDB",
    #     "thumb": "img/habit-tracking.png",
    #     "hero": "img/habit-tracking-hero.png",
    #     "categories": ["python", "web"],
    #     "slug": "habit-tracking",
    #     "prod": "https://udemy.com",
    # },
]

slug_to_project = {project["slug"]: project for project in projects}


@pages.route("/")
def home():
    return render_template("projects.html", projects=projects)


@pages.route("/about")
def about():
    return render_template("about.html")


@pages.route("/contact")
def contact():
    return render_template("contact.html")


@pages.route("/project/<string:slug>")
def project(slug):
    if slug not in slug_to_project:
        abort(404)
    return render_template(
        f"project_{slug}.html",
        project=slug_to_project[slug],
    )


@pages.errorhandler(404)
def page_not_found(error):
    return render_template("404.html"), 404

portfolio/templates/about.html
{% extends "base.html" %}

{% block content %}
<main class="main main--about">
    <div class="profile--picture">
        <img src="{{ url_for('static', filename='img/display.png') }}" alt="Profile Picture" />
    </div>
    <div class="about--text">
        <p>
            I am Muhammad Ammar, a recent graduate from the National University of Sciences and Technology with a
            Bachelor's
            degree in Mechanical Engineering. Throughout my academic journey, I developed a keen interest in
            problem-solving
            and data analysis, which propelled me towards pursuing a career in the field of intelligent robotics,
            machine
            learning, and artificial intelligence.
        </p>
        <p>
            During my undergraduate studies, I undertook a significant project focusing on the design and development of
            an
            <a class="main__link" href="{{ url_for('pages.project', slug='amr') }}">Autonomous Mobile Robot</a>. This project
            not
            only showcased my technical skills but also ignited my curiosity in intelligent robotics, prompting me to
            delve
            deeper into the realms of machine learning and artificial intelligence.
        </p>
        <p>
            Since completing my degree, I have been actively enhancing my expertise in the fields of machine learning
            and
            computer vision. I embarked on the Machine Learning Specialization offered by DeepLearningAI, which served
            as a
            foundation for understanding the fundamental concepts of machine learning. Additionally, I delved into
            computer
            vision, beginning with OpenCV and gradually progressing to advanced deep learning algorithms such as YOLO
            and
            SSD. As a result, I have acquired a robust skill set in these domains, proficiently utilizing major
            libraries
            such as scikit-learn, Keras, and PyTorch. Furthermore, I possess knowledge of model optimization techniques
            and
            have implemented numerous personal projects to further refine my skills.
        </p>
        <p>
            To augment my professional competencies, I am currently focused on expanding my knowledge in web
            development. I
            have gained proficiency in HTML and CSS for frontend development, alongside utilizing Flask for backend
            development and MongoDB for database management. My experience in building various basic websites has
            equipped
            me with the necessary skills to transition into this field professionally, allowing me to leverage my
            existing
            skill set in conjunction with my passion for machine learning.
        </p>
        <p>
            Presently, I am seeking an entry-level position that aligns with my skill sets. My ideal workplace would
            enable
            me to train machine learning models and deploy them into production through the medium of web development.
            This
            dynamic environment would not only utilize my existing proficiencies but also provide me with the
            opportunity to
            gain expertise in areas that are currently less familiar to me, such as MLOps and model deployment. However,
            as
            I am still in the nascent stage of my professional journey, I am open to roles that enable me to further
            develop
            my skills in machine learning engineering, web development, or production analysis.
        </p>
        <p>
            In conclusion, I am a motivated individual with a strong foundation in mechanical engineering, combined with
            a
            growing skill set in machine learning, computer vision, and web development. I am eager to contribute to a
            fast-paced industry, utilizing my problem-solving abilities and passion for data analysis to make a positive
            impact. I am confident that my enthusiasm and dedication, coupled with my continuous learning mindset, will
            enable me to thrive in a professional setting.
        </p>
    </div>
</main>
{% endblock %}

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Muhammad Ammar | Portfolio</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://font.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for ('static', filename='css/styles.css') }}" />
</head>

<body>
    <header class="header">
        <h1>Muhammad Ammar</h1>

        <nav class="nav">
            <a href="{{ url_for('pages.home') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.home') }}">
                Projects
            </a>
            <a href="{{ url_for('pages.about') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.about') }}">
                About
            </a>
            <a href="{{ url_for('pages.contact') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.contact') }}">
                Contact
            </a>
        </nav>
    </header>
    {% block content %}

    {% endblock %}
</body>

</html>

portfolio/templates/contact.html
{% extends "base.html" %}

{% block content %}
<main class="main main--content">
    <dl>
        <div class="contact">
            <dt>Email:</dt>
            <dd class="contact__details">
                <a class="contact__link" href="mailto:muhammad2000ammar@gmail.com">
                    muhammad2000ammar [at] gmail.com
                </a>
            </dd>
        </div>
        <div class="contact">
            <dt>LinkedIn:</dt>
            <dd class="contact__details">
                <a class="contact__link" href="https://www.linkedin.com/in/muhammad2000ammar/">
                    @muhammad2000ammar
                </a>
            </dd>
        </div>
        <div class="contact">
            <dt>GitHub:</dt>
            <dd class="contact__details">
                <a class="contact__link" href="https://github.com/Ammar2k">
                    @Ammar2k
                </a>
            </dd>
        </div>
    </dl>
</main>
{% endblock %}

portfolio/templates/project_amr.html
{% extends "base.html" %}

{% block content %}
<main class="main main--project">
    <div>
        <img class="hero hero--amr" src="{{ url_for('static', filename=project['hero']) }}" alt="picture of the AMR" />

        <article class="project">
            <article class="project__content">
                <h2 class="project__heading">{{ project['name'] }}</h2>

                <p>
                    My final year project was the design and development of an Autonomous Mobile Robot with an automated
                    devlivery mechanism for use in warehouses. For this project, I worked in the Robotics and
                    Intelligent Systems Engineering (R.I.S.E) Lab under the supervision of
                    <a class="main__link" href="https://sites.google.com/view/kfiqbal">Dr. Khawaja Fahad
                        Iqbal</a>.
                </p>
                <p>
                    The robot made use of a differential wheel drive for locomotion. The automated delivery mechanism
                    used automated rollers which detected the presence of the object at pickup, loaded them to the
                    center of the platform, and dropped them off at the designated endpoint.
                </p>
                <p>
                    My part in the project was to focus on the concept development, and programming of the mobile robot.
                    For obstacle detection, the robot used ultrasonic sensors. For distance tracking, wheel encoders
                    were used. IR sensors were used for delivery object tracking. Arduino was used as the processing
                    unit for this project.
                </p>
                <p>
                    The results of the project were presented and published at the Applied Human Factors and Ergonomics
                    Conference (2022) titled <a class="main__link"
                        href="https://openaccess.cms-conferences.org/publications/book/978-1-958651-11-7/article/978-1-958651-11-7_5">A
                        Chain-Driven Live Roller Mechanism for Loading and
                        Unloading Packages on Autonomous Mobile Robots in Warehouses.</a>
                    I was responsible for the technical writing of the paper, and was designated as the primary author
                    of the paper.
                </p>
            </article>
            <section>
                <article class="project__meta-group">
                    <h3 class="project__heading project__heading--meta">Technologies used</h3>

                    <ul class="technology-list">
                        <li class="technology-list__item">Robotics</li>
                        <li class="technology-list__item">Manufacturing Processes</li>
                        <li class="technology-list__item">Arduino Programming</li>
                    </ul>
                </article>

                <a class="cta" href="{{ project['prod'] }}">
                    <img class="cta__icon" src="{{ url_for('static', filename='img/pointer.svg') }}">
                    Read more here.
                </a>
            </section>
        </article>
    </div>
</main>
{% endblock %}

portfolio/templates/project_habit-tracking.html
{% extends "base.html" %}

{% block content %}
<main class="main main--project">
    <div>
        <img class="hero" src="{{ url_for('static', filename=project['hero']) }}"
            alt="A hand holding a pen, about to write something" />

        <article class="project">
            <article class="project__content">
                <h2 class="project__heading">{{ project['name'] }}</h2>

                <p>
                    Hi, I'm Ammar! I am currently a beginner to web development.
                    My goal is to eventually build websites that will call ML
                    projects that I create and provides users with a GUI to use them
                    by performing inference on their images.
                </p>
            </article>
            <section>
                <article class="project__meta-group">
                    <h3 class="project__heading project__heading--meta">Technologies used</h3>

                    <ul class="technology-list">
                        <li class="technology-list__item">Python</li>
                        <li class="technology-list__item">HTML</li>
                        <li class="technology-list__item">CSS</li>
                    </ul>
                </article>

                <a class="cta" href="{{ project['prod'] }}">
                    <img class="cta__icon" src="{{ url_for('static', filename='img/pointer.svg') }}">
                    View in production
                </a>
            </section>
        </article>
    </div>


</main>
{% endblock %}

portfolio/templates/project_highway_lane_detection.html
{% extends "base.html" %}

{% block content %}
<main class="main main--project">
    <div>
        <img class="hero hero--highway" src="{{ url_for('static', filename=project['hero']) }}"
            alt="picture of the highway lanes" />

        <article class="project">
            <article class="project__content">
                <h2 class="project__heading">{{ project['name'] }}</h2>

                <p>
                    I undertook a project focused on highway lane detection, which involved the development of an
                    algorithm to identify and highlight the lanes on a road in a given video. The goal was to provide a
                    visual representation of the lanes, aiding in navigation and ensuring driver safety.
                </p>
                <p>
                    To accomplish this, I utilized the OpenCV library, which provides a wide range of computer vision
                    functions. The main steps of the lane detection algorithm are as follows:
                </p>
                <ol>
                    <li>Preprocessing: The input video frames were initially converted from color to grayscale using the
                        <code>cv2.cvtColor()</code> function. This step simplifies subsequent image processing
                        operations.
                    </li>
                    <li>Edge Detection: To identify the edges of the lanes, I employed the Canny edge detection
                        algorithm, accessible through the <code>cv2.Canny()</code> function. This algorithm identifies
                        regions of rapid intensity changes in the grayscale image, highlighting the boundaries of
                        objects.</li>
                    <li>Region of Interest: Since we are primarily interested in the lower region of the video frames
                        where the driving lanes are located, a region of interest (ROI) was defined. This triangular ROI
                        was specified by selecting three points: the bottom left, bottom right, and upper center of the
                        frame. The <code>region_of_interest()</code> function used the ROI coordinates to create a mask,
                        effectively removing all other regions from further processing.</li>
                    <li>Line Detection: The Hough Transform method was employed to detect lines within the ROI. The
                        <code>cv2.HoughLinesP()</code> function was utilized, which utilizes a probabilistic variant of
                        the Hough Transform to detect line segments. The detected lines were stored as sets of
                        endpoints, defining their start and end coordinates.
                    </li>
                    <li>Visualization: To provide a clear representation of the detected lanes, the
                        <code>draw_the_lines()</code> function was implemented. This function created a separate image
                        with black background and drew the detected lane lines in blue. The resulting image was then
                        merged with the original frame using the <code>cv2.addWeighted()</code> function, allowing the
                        lane lines to be displayed prominently.
                    </li>
                </ol>
                <p>
                    Finally, the processed frames were displayed as a video using the <code>cv2.imshow()</code> function
                    within a while loop. Each frame was processed by the lane detection algorithm, resulting in a
                    real-time visualization of the detected lanes. The video playback was controlled using the
                    <code>cv2.waitKey()</code> function.
                </p>
                <p>
                    By implementing this highway lane detection project, I was able to successfully identify and
                    highlight the driving lanes in a given video. This algorithm can be further optimized and integrated
                    into autonomous driving systems, advanced driver assistance systems (ADAS), and other applications
                    aimed at improving road safety and navigation.
                </p>
            </article>
            <section>
                <article class="project__meta-group">
                    <h3 class="project__heading project__heading--meta">Technologies used</h3>

                    <ul class="technology-list">
                        <li class="technology-list__item">Compuer Vision</li>
                        <li class="technology-list__item">OpenCV</li>
                        <li class="technology-list__item">Python</li>
                    </ul>
                </article>

                <a class="cta" href="{{ project['prod'] }}">
                    <img class="cta__icon" src="{{ url_for('static', filename='img/pointer.svg') }}">
                    Access code here.
                </a>
            </section>
        </article>
    </div>
</main>
{% endblock %}

portfolio/templates/project_traffic_sign_classification.html
{% extends "base.html" %}

{% block content %}
<main class="main main--project">
    <div>
        <img class="hero hero--highway" src="{{ url_for('static', filename=project['hero']) }}"
            alt="picture of the traffic signs" />

        <article class="project">
            <article class="project__content">
                <h2 class="project__heading">{{ project['name'] }}</h2>

                <p>
                    The Traffic Sign Classification Algorithm is a deep learning model designed to identify and classify
                    various traffic signs. The algorithm utilizes a Convolutional Neural Network (CNN) architecture,
                    implemented using the Keras library. The model is trained on a dataset consisting of images of
                    different traffic signs.
                </p>
                <p>
                    The algorithm starts by importing the necessary libraries and setting the parameters such as the
                    path to the dataset, batch size, and image dimensions. The dataset is then imported and split into
                    training, validation, and test sets. Data preprocessing techniques, such as grayscale conversion,
                    histogram equalization, and normalization, are applied to enhance the images' features and prepare
                    them for training.
                </p>
                <p>
                    Next, the model architecture is defined, consisting of multiple convolutional and pooling layers
                    followed by fully connected layers. Dropout layers are also incorporated to prevent overfitting. The
                    model is compiled using the Adam optimizer and trained on the training set. The training progress is
                    monitored and visualized using plots for loss and accuracy.
                </p>
                <p>
                    After training, the model is evaluated on the test set to assess its performance. The test score and
                    accuracy are displayed. Additionally, the trained model is saved as a pickle object for future use.
                </p>
                <p>
                    Overall, the Traffic Sign Classification Algorithm demonstrates the effectiveness of CNNs in
                    accurately identifying and classifying traffic signs, making it a valuable tool for traffic
                    management and autonomous driving systems.
                </p>
            </article>
            <section>
                <article class="project__meta-group">
                    <h3 class="project__heading project__heading--meta">Technologies used</h3>

                    <ul class="technology-list">
                        <li class="technology-list__item">Keras</li>
                        <li class="technology-list__item">OpenCV</li>
                        <li class="technology-list__item">Python</li>
                    </ul>
                </article>

                <a class="cta" href="{{ project['prod'] }}">
                    <img class="cta__icon" src="{{ url_for('static', filename='img/pointer.svg') }}">
                    Access code here.
                </a>
            </section>
        </article>
    </div>
</main>
{% endblock %}

portfolio/templates/projects.html
{% extends "base.html" %}

{% block content %}
<main class="main main--home">
    <section class="projects">
        {% for project in projects %}
        <a class="u-bare-link" href="{{ url_for('pages.project', slug=project['slug']) }}">
            <article class="project-card">
                <img class="project-card__images" src="{{ url_for('static', filename=project['thumb']) }}"
                    alt="{{ project['name'] }} hero image" />
            </article>
            <header class="project-card__meta">
                <ul class="categories">
                    {% for category in project['categories'] %}
                    <li class="categories__tag">{{ category }}</li>
                    {% endfor %}
                </ul>

                <h2 class="project-card__name">{{ project['name'] }}</h2>
            </header>
        </a>
        {% endfor %}
    </section>
</main>
{% endblock %}